###########################################################
### Welcome to Beautiful Jekyll!

title: Christian Taillon
author: Christian Taillon
email: christiantaillon@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  # write desc
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://christiant.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: christian_tail
github_username:  christian-taillon

# Navigation Bar
navbar-links:
  Cyber Security Resources: "cyberresources"
  Splunk & KQL:
    Splunk Cheatsheet: "spl"
    Splunk Beginner Cheatsheet: "spl-beginner"
    KQL Guide: "kql-guide"
  Configurations:
    - RC Files: "rc-files"
    - Atom Conf: "atomconf"
    - Splunk Docker: "splunkdocker"
    - ParetoPi: "paretopi"
  Interview Resources:
    - Interview: "interview"
    - SOC Interview: "socinterview"
    - Security Engineer: "securityengineer"
    - Threat Hunter: "th-interview"
  About: "about"

# Build settings
# theme: minima
remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# markdown processor
timezone: "America/Phoenix"
highlighter: rouge
markdown: kramdown

# Collections
collections:
#   - medium_posts
#   - infosecresources
#   - spl-cheat
#   - "Splunk SPL Cheat Sheet"
#   - spl

# General
  twitter: true
  facebook: true
  linkedin: true

  url-pretty: "christiant.io"

  excerpt_length: 50
  feed_show_excerpt: true
  feed_show_tags: true
  post_search: true

######################################
# --- Colours / background image --- #
######################################

# Personalize the colours in your website. Colour values can be any valid CSS colour

# navbar-col: "#EAEAEA"
# navbar-text-col: "#404040"
# navbar-border-col: "#DDDDDD"
# page-col: "#FFFFFF"
# text-col: "#404040"
# link-col: "#008AFF"
# hover-col: "#0085A1"
# footer-col: "#EAEAEA"
# footer-text-col: "#777777"
# footer-link-col: "#404040"
# footer-hover-col: "#0085A1"

# Footer

social-network-links:
  email: "	christiantaillon@pm.me "
  #rss: true  # remove this line if you don't want to show an RSS link at the bottom
  facebook: christianjtaillon
  github: christian-taillon
  twitter_username: christian_tail
  medium: christiantaillon
  linkedin: christiantaillon
  stackoverflow: christian-taillon


  #rss: true  # remove this line if you don't want to show an RSS link at the bottom
  # If you want your website to generate an RSS feed, provide a description
  # The URL for the feed will be https://<your_website>/feed.xml
  #rss-description: This website is a virtual proof that I'm awesome

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
