###########################################################
### Welcome to Beautiful Jekyll!

title: Christian Taillon
author: Christian Taillon
email: christiantaillon@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  # write desc
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://christiant.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: christian_tail
github_username:  christian-taillon

# Navigation Bar
navbar-links:
  Generative AI for InfoSec:
    - AI Ally: "ai-infosec"
    - OpenAI-CL Tool: "https://github.com/christian-taillon/openai-cl"
  Threat Hunting:
    - "Part-time Threat Hunting: Considering its Efficacy" : https://christiantaillon.medium.com/part-time-threat-hunting-considering-its-efficacy-85598a9d339
    - "Prophet Spider Exploits Citrix ShareFile to Deploy Webshell" : https://christiantaillon.medium.com/prophet-spider-exploits-citrix-sharefile-to-deploy-webshell-d2689abd4301
    - "QakBot Detection: DUCK HUNT" : https://christiantaillon.medium.com/qakbot-detection-duck-hunt-aa0cadb398a7
    - "QakBot Hunting: Autumn Spice" : https://christiantaillon.medium.com/qakbot-part-3-6497bd412d39
    - "QakBot Detection: DUCK HUNT Part 2 — The .LNK" : https://christiantaillon.medium.com/qakbot-detection-duck-hunt-part-2-a93ea2498211
    - Log4j: https://github.com/christian-taillon/log4shell-hunting
    - Sunburst: https://github.com/christian-taillon/sunburst-hunting
    - Various Search Leads: https://github.com/christian-taillon/threat-hunting-searches
    - "What do we actually know about the Darkside Ransomware operators?" : https://christiantaillon.medium.com/what-do-we-actually-know-about-the-darkside-ransomware-operators-5a1523094899
    - "GitHub Actions Abuse by Cryptominers" : https://christiantaillon.medium.com/github-actions-abuse-by-cryptominers-8492e88e1400
  Blue Team Tools:
    - Splunk Cheatsheet: "spl"
    - Splunk Beginner Guide: "spl-beginner"
    - KQL Beginner Guide: "kql-guide"
    - Sigma Rule Guide: "sigma-rule-guide"
    - ClamAV Guide: "clamav-guide"
    - YARA Rule Guide: "yara-rule-guide"
    - SNORT Rule Guide: "snort-suricata-guide"
    - InfoSec: "infosec"
    - Cyber Security Resources: "cyberresources"
    - Gist/christian-taillon: https://gist.github.com/christian-taillon
    - Endpoint Forensics: "ep-forensics"
  Red Team:
    -  Atomic: "atomic"
    - "Sith CheatSheet: Kali" : "sith-cheatsheet"
    - Recon-ng Guide: "recon-ng"
    - DNS OSINT PDF: "https://christiant.io/download/dns-guide-awnsers.pdf"
  Conf & Dev:
    - Git CheatSheet: "git-cheatsheet"
    - RC Files: "rc-files"
    - Splunk Docker: "splunkdocker"
    - ParetoPi: "paretopi"
    - DockerPihole: "https://github.com/christian-taillon/docker-pihole"
    - Splunk Windows Forwarder: "https://github.com/christian-taillon/splunk_win_uf"
    - Simple Guide to Python3 Virtual Environments: "pyhon3virt"
  Interview Resources:
    - Interview: "interview"
    - SOC Interview: "socinterview"
    - Security Engineer: "securityengineer"
    - Threat Hunter: "th-interview"
  About Me: "about"
# Build settings
# theme: minima
remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# markdown processor
timezone: "America/Phoenix"
highlighter: rouge
markdown: kramdown

# Collections
collections:
#   - medium_posts
#   - infosecresources
#   - spl-cheat
#   - "Splunk SPL Cheat Sheet"
#   - spl

# General
  twitter: true
  facebook: true
  linkedin: true

  url-pretty: "christiant.io"

  excerpt_length: 50
  feed_show_excerpt: true
  feed_show_tags: true
  post_search: true

######################################
# --- Colours / background image --- #
######################################

# Personalize the colours in your website. Colour values can be any valid CSS colour

# navbar-col: "#EAEAEA"
# navbar-text-col: "#404040"
# navbar-border-col: "#DDDDDD"
# page-col: "#FFFFFF"
# text-col: "#404040"
# link-col: "#008AFF"
# hover-col: "#0085A1"
# footer-col: "#EAEAEA"
# footer-text-col: "#777777"
# footer-link-col: "#404040"
# footer-hover-col: "#0085A1"

# Footer

social-network-links:
  email: "	cpublic@christiant.io "
  #rss: true  # remove this line if you don't want to show an RSS link at the bottom
  facebook: christianjtaillon
  github: christian-taillon
  twitter_username: christian_tail
  medium: christiantaillon
  linkedin: christiantaillon
  stackoverflow: 15532834


  #rss: true  # remove this line if you don't want to show an RSS link at the bottom
  # If you want your website to generate an RSS feed, provide a description
  # The URL for the feed will be https://<your_website>/feed.xml
  #rss-description: This website is a virtual proof that I'm awesome

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
