###########################################################
### Welcome to Beautiful Jekyll!

title: Christian Taillon
author: Christian Taillon
email: public@christiant.io@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  # write desc
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://christiant.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: christian_tail
github_username:  christian-taillon

# Navigation Bar
navbar-links:
  Information Security:
    - Phoenix2025 : "2025"
    - Splunk Cheatsheet: "spl"
    - Splunk Beginner Guide: "spl-beginner"
    - KQL Beginner Guide: "kql-guide"
    - LogScale : "logscale_beg_guide"
    - LogScale Cheatsheet : "logscale"
    - Sigma Rule Guide: "sigma-rule-guide"
    - ClamAV Guide: "clamav-guide"
    - YARA Rule Guide: "yara-rule-guide"
    - SNORT Rule Guide: "snort-suricata-guide"
    - Cyber Security Resources: "cyberresources"
    - Gist/christian-taillon: https://gist.github.com/christian-taillon
    - Endpoint Forensics: "ep-forensics"
    - Atomic: "atomic"
    - "Sith CheatSheet: Kali" : "sith-cheatsheet"
    - Recon-ng Guide: "recon-ng"
    - DNS OSINT PDF: "https://christiant.io/download/dns-guide-awnsers.pdf"
  Threat Hunting and Intel:
    - APTTracker.md: "https://github.com/christian-taillon/apt-tracker-md"
    - Detect-AutoIT: "https://github.com/christian-taillon/detect-autoit"
    - SigmaGUI: "https://github.com/christian-taillon/SigmaGUI"
    - "Part-time Threat Hunting: Considering its Efficacy" : https://christiantaillon.medium.com/part-time-threat-hunting-considering-its-efficacy-85598a9d339
    - "Prophet Spider Exploits Citrix ShareFile to Deploy Webshell" : https://christiantaillon.medium.com/prophet-spider-exploits-citrix-sharefile-to-deploy-webshell-d2689abd4301
    - "QakBot Detection: DUCK HUNT" : https://christiantaillon.medium.com/qakbot-detection-duck-hunt-aa0cadb398a7
    - "QakBot Hunting: Autumn Spice" : https://christiantaillon.medium.com/qakbot-part-3-6497bd412d39
    - "QakBot Detection: DUCK HUNT Part 2 — The .LNK" : https://christiantaillon.medium.com/qakbot-detection-duck-hunt-part-2-a93ea2498211
    - Log4j: https://github.com/christian-taillon/log4shell-hunting
    - Sunburst: https://github.com/christian-taillon/sunburst-hunting
    - Various Search Leads: https://github.com/christian-taillon/threat-hunting-searches
    - "What do we actually know about the Darkside Ransomware operators?" : https://christiantaillon.medium.com/what-do-we-actually-know-about-the-darkside-ransomware-operators-5a1523094899
    - "GitHub Actions Abuse by Cryptominers" : https://christiantaillon.medium.com/github-actions-abuse-by-cryptominers-8492e88e1400 
  Dev and Projects:
    - Splunk Docker: "splunkdocker"
    - Git CheatSheet: "git-cheatsheet"
    - RC Files: "rc-files"
    - AutoIT-Seeker: "https://github.com/christian-taillon/AutoIT-Seeker"
    - ParetoPi: "paretopi"
    - DockerPihole: "https://github.com/christian-taillon/docker-pihole"
    - Splunk Windows Forwarder: "https://github.com/christian-taillon/splunk_win_uf"
    - Programing Basics: "program-concept"
    - Python3 Virtual Environments: "pyhon3virt"
    - File Arramgeent and Sorting Tool: "https://github.com/christian-taillon/fast"
    - APTTracker.md: "https://github.com/christian-taillon/apt-tracker-md"
    - Detect-AutoIT: "https://github.com/christian-taillon/detect-autoit"
    - SigmaGUI: "https://github.com/christian-taillon/SigmaGUI"
  Machine Learning and AI:
    - Llama Guard: "llama_guard"
    - Token Guard: "token_guard"
    - OpenWebUI Releases: "https://openwebui.com/u/christiant/"
    - AI Pipelines: "https://github.com/christian-taillon/openweb_ui_dev"
    - LLM Distillery: "https://github.com/christian-taillon/llm-distillery"
    - Bean-Counter: "https://github.com/christian-taillon/bean-counter"
    - OpenAI-CL Tool: "https://github.com/christian-taillon/openai-cl"
    - Scanned Models: "models"
    - LLM Security: "llm_security"
    - Guide Running Local LLMs: "localllm"
    - Generative AI Use in InfoSec: "ai-infosec"
    - Building a Private GenAI Team: "https://christiant.io/download/Building a Private GenAI Team with Open-Source Models.pdf"
    - Corporate Generative AI Risk Mitigation: "https://christiant.io/download/GenerativeAI Risk Mitigation.pdf"
    - vLLM: "vLLM"
  Interview Resources:
    - Interview: "interview"
    - SOC Interview: "socinterview"
    - Security Engineer: "securityengineer"
    - Threat Hunter: "th-interview"
    - InfoSec Resources: "https://github.com/christian-taillon/infosec-resources"
  About Me: "about"
  # Resume: resume

# Build settings
# theme: minima
# remote_theme: mmistakes/minimal-mistakes
remote_theme: daattali/beautiful-jekyll
plugins:
#  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
# markdown processor
timezone: "America/Phoenix"
highlighter: rouge
markdown: kramdown

# Collections
#collections:
#   - medium_posts
#   - infosecresources
# - spl-cheat
# - "Splunk SPL Cheat Sheet"
# - spl

# General
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

  url-pretty: "christiant.io"

  excerpt_length: 50
  feed_show_excerpt: true
  feed_show_tags: true
  post_search: true

# --- Google Analytics --- #
gtag: "G-R34BHCHXE0"

keywords: "cyber,infosec,splunk,christian,christian-taillon,taillon,ai,llm,information,security,information security"

######################################
# --- Colours / background image --- #
######################################

navbar-col: "#0e0e0e"
navbar-text-col: "#FFFFFF"
navbar-border-col: "#0e0e0e"
page-col: "#FFFFFF"
text-col: "#0e0e0e"
link-col: "#fcc624"
hover-col: "#fcc624"
footer-col: "#0e0e0e"
footer-text-col: "#FFFFFF"
footer-link-col: "#fcc624"
footer-hover-col: "#fcc624"

################
# --- Logo --- #
################

# avatar: "/image/coffee_logo.jpeg"

# --- Footer options --- #
social-network-links:
  email: "public@christiant.io "
  #rss: true  # remove this line if you don't want to show an RSS link at the bottom
  facebook: christianjtaillon
  github: christian-taillon
  twitter_username: christian_tail
  medium: christiantaillon
  linkedin: christiantaillon
  #stackoverflow: 15532834


  #rss: true  # remove this line if you don't want to show an RSS link at the bottom
  # If you want your website to generate an RSS feed, provide a description
  # The URL for the feed will be https://<your_website>/feed.xml
  #rss-description: This website is a virtual proof that I'm awesome

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

prose:
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - /_includes
    - /_layouts
    - /css
    - /img
    - /js